name: Release Firmware

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0, v2.1.3, etc.

jobs:
  package-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install -r requirements.txt || true

      - name: Make script executable
        run: chmod +x ./prepare_release.sh

      - name: Run packaging
        run: ./prepare_release.sh

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Firmware ${{ github.ref_name }}
          body: |
            Firmware release for version `${{ github.ref_name }}`.
            Includes the compressed image and metadata.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload firmware image
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/firmware.tar.zlib
            release/image-info.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
